name: Build and Package iOS Workspace
 
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
 
jobs:
  build:
    runs-on: macOS-latest
 
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
 
    - name: Setup Xcode
      uses: boricsun/xcode-install-action@v2.2.1
      with:
        xcodeVersion: '15.3'
 
    - name: Setup Fastlane
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x
 
    - name: Install Dependencies
      run: bundle install
 
    - name: Build and Package Workspace
      run: fastlane ios workspace_build scheme:"testbuild"
 
      env:
        DISABLE_SPRING_SPEED_UP_MESSAGE: 'true'
